export const LISTINGS_SERVICE_URL = process.env.LISTINGS_SERVICE_URI;
export const LISTINGS_SERVICE_PORT = process.env.LISTINGS_SERVICE_PORT;
export const LISTINGS_SERVICE_URI =
  LISTINGS_SERVICE_URL + ":" + LISTINGS_SERVICE_PORT;

export const USERS_SERVICE_URL = process.env.USERS_SERVICE_URI;
export const USERS_SERVICE_PORT = process.env.USERS_SERVICE_PORT;
export const USERS_SERVICE_URI = USERS_SERVICE_URL + ":" + USERS_SERVICE_PORT;
