version: "3"
services:
  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=password
    ports:
      - 7100:7100
    volumes: # if we make some change, thanks to volumes change will be changed in container immediately
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - TYPEORM_USERNAME=root
      - TYPEORM_PASSWORD=password
    ports:
      - 7101:7101
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - 0.0.0.0:7201:3306
